services:
  7dtd-server:
    build: .
    ports:
      - "26900-26902:26900-26902/udp"
      - "8080:8080"
    environment:
      - ServerName=DadsCrazyServer
      - ServerVisibility=0
      - GameWorld=RWG
      - WorldGenSeed=Afunseed
      - WorldGenSize=8192
      - GameName=dads_game
    volumes:
      - ./server_data:/steamapps
