# Vanilla 7DTD deployment & configuration
# Add any valid serverconfig.xml property key and value 
# to the environment variables to override the default
# values
services:
  7dtd-server:
    build: .
    ports:
      - "26900-26902:26900-26902/udp"
      - "8080:8080"
    environment:
      - ServerName=Dad's Crazy Server
      - ServerVisibility=0
      - GameWorld=RWG
      - WorldGenSeed=Afunseed
      - WorldGenSize=8192
      - GameName=dads_game
      - MODE=server             # Change to "manual" to prevent auto-start
      - VALIDATE=false          # Change this to true to enable steam install validation
    volumes:
      - ./server_data:/steamapps
